# Plot
from .axes_from_axes import axes_from_axes  # noqa
from .figcolorbar import figcolorbar  # noqa
from .fixedpointcolornorm import FixedPointColorNorm  # noqa
from .get_aspect import get_aspect  # noqa
from .get_stats_label_length import get_stats_label_length  # noqa
from .get_continuous_cmap import get_continuous_cmap  # noqa
from .hex2rgb import hex_to_rgb  # noqa
from .hudsondiamondaxes import hdaxes  # noqa
from .midpointcolornorm import MidpointNormalize  # noqa
from .midpointlognorm import MidPointLogNorm  # noqa
from .multiple_formatter import multiple_formatter  # noqa
from .multiple_formatter import Multiple  # noqa
from .nice_colorbar import nice_colorbar  # noqa
from .pick_colors_from_cmap import pick_colors_from_cmap  # noqa
from .pick_data_from_image import pick_data_from_image  # noqa
from .plot_binnedstats import plot_binnedstats  # noqa
from .plot_font import plot_font  # noqa
from .plot_label import plot_label  # noqa
from .plot_xyz_line import plot_xyz_line  # noqa
from .pz_figure import pz_figure  # noqa
from .remove_ticklabels import remove_xticklabels  # noqa
from .remove_ticklabels import remove_yticklabels  # noqa
from .remove_ticklabels import remove_ticklabels  # noqa
from .remove_ticklabels import remove_ticks  # noqa
from .remove_ticklabels import remove_ticklabels_bottomleft  # noqa
from .remove_ticklabels import remove_ticklabels_topright  # noqa
from .remove_ticklabels import remove_topright  # noqa
from .rgb2dec import rgb_to_dec  # noqa
from .right_align_legend import right_align_legend  # noqa
from .scatter_hist import scatter_hist  # noqa
from .scatterlegend import scatterlegend  # noqa
from .smooth_nan_image import smooth_nan_image  # noqa
from .trendline import Trendline  # noqa
from .updaterc import updaterc  # noqa
from .updaterc import updaterc_pres  # noqa
from .update_colorcycler import update_colorcycler  # noqa
from .view_colormap import view_colormap  # noqa
from .zerotraceaxes import ztaxes  # noqa
