channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - ipython
  - pytest
  - matplotlib
  - numpy
  - mypy
  - autopep8
  - scipy
  - cartopy
  - netcdf4
  - gdal
  - obspy
  - pip
  - pip:
    - xarray
    - beautifulsoup4
    - pyyaml
    - sphinx
    - sphinx_book_theme
    - numpydoc
    - -e .
